name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, check and build app
        run: |
          npm install
          npm run build
      - name: Update matching Github page
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.email "hello@dagoma3d.com"
          git config --global user.name "dagoma3d"
          git clone "https://dagoma3d:$API_TOKEN_GITHUB@github.com/dagoma3d/dagoma3d.github.io.git"
          rm -rf ./dagoma3d.github.io/*
          cp -r ./build/* ./dagoma3d.github.io/
          cd dagoma3d.github.io
          git add .
          git commit -am "Update from github actions"
          git push
