name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, check and build app
        run: |
          npm install
          npm run build
      - name: Update matching Github page
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.email "wael@dagoma.fr"
          git config --global user.name "waelabd"
          git clone "https://github.com/dagoma3d/dagoma3d.github.io.git"
          rm -rf ./dagoma3d.github.io/*
          cp -r ./build/* ./dagoma3d.github.io/
          cd dagoma3d.github.io
          git add .
          git commit -am "${HEAD_COMMIT_MESSAGE:=Manual Worflow Commit}"
          git push
